### ISSUE TITLE
LookupError: 'tstop' is not a defined hoc variable name

### ISSUE THREAD

**Issue by cytheria43** [orena1/NEURON_tutorial#2]
Hi,

I followed  the instruction and have compiled the mods.However ,a LookupError happened when I tried to run the example in Jupyter Notebook.

```
---------------------------------------------------------------------------
LookupError                               Traceback (most recent call last)
<ipython-input-6-0f2c77b59e6a> in <module>
----> 1 h.tstop = 220
      2 h.dt = 0.025
      3 h.v_init=-70
      4 h.run()

LookupError: 'tstop' is not a defined hoc variable name.
```
Any idea what I'm doing wrong? Otherwise,I use` pip3 install neuron` instead of downloading the NEURON installer.

**Comment by cytheria43** [comment]
Have updated the jupyter code corresponding to the latest version of NEURON. It uses ` h.finitialize()` and  `h.continuerun()`instead.

**Comment by orena1** [comment]
Hi!
It works for me:
![image](https://user-images.githubusercontent.com/8983713/115784721-2a64ca80-a3c7-11eb-8de7-452106d8b24d.png)

I've also installed using pip

Which example does not work for you?
